
counter: counter.c
	gcc -Wall -o counter counter.c -lpthread

array: counter_array.c
	gcc -Wall -o array counter_array.c -lpthread

mutex: counter_mutex.c
	gcc -Wall -o mutex counter_mutex.c -lpthread
