ex_compile: ex_compile.c
	gcc -Wall -o ex_compile ex_compile.c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lglib-2.0  

word_count: word_count.c
	gcc -Wall -o word_count word_count.c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lglib-2.0
